package com.cargill.customerfacing.dscportal.domain;

public interface DSCConstands {
	
	public static final String APPLICATION_JSON = "application/json";
	public static final String MULTIPART_FORMDATA = "multipart/form-data";
	public static final String APPLICATION_PDF = "application/pdf";
	public static final String CUST_PROFILE_SELECT_QUERY = "SELECT * FROM USER_PROFILE WHERE CUSTOMER_ID =?";
	public static final String CUST_PROFILE_INSERT_QUERY = "INSERT INTO USER_PROFILE(USER_ID,EMAIL,FIRSTNAME,LASTNAME,LANGUAGE,CUSTOMER_ID,ACTIVE_FLAG,CARGILL_USER) VALUES(?,?,?,?,?,?,?,?)";
	public static final String CUST_PROFILE_UPDATE_QUERY = "UPDATE VIETNAMDSC.USER_PROFILE SET USER_ID=?,EMAIL=?,FIRSTNAME=?,LASTNAME=?,LANGUAGE=?,CUSTOMER_ID=?,ACTIVE_FLAG=?,CARGILL_USER=? WHERE USER_ID =?";
	public static final String STATUS_SELECT_QUERY = "SELECT * FROM STATUS WHERE STATUS_ID =?";
	public static final String STATUS_INSERT_QUERY = "INSERT INTO STATUS(STATUS_ID,STATUS_TYPE,DESCRIPTION) VALUES(?,?,?)";
	public static final String SERVICE_CONTRACTS_SELECT_QUERY = "SELECT * FROM SERVICE_CONTRACTS WHERE CAK_NO =?";
	public static final String SERVICE_CONTRACTS_INSERT_QUERY = "INSERT INTO SERVICE_CONTRACTS(CAK_NO,CAK_DATE,COMMODITY,QUANTITY,RECEIVED,BALANCE_STOCK,CONTRACT_TYPE,CUSTOMER_ID) VALUES(?,?,?,?,?,?,?,?)";
	public static final String PICKUP_SCHEDULE_SELECT_QUERY = "SELECT * FROM PICKUP_SCHEDULE WHERE CAK_NO=?";
	public static final String PICKUP_SCHEDULE_INSERT_QUERY = "INSERT INTO PICKUP_SCHEDULE(DATE,PICKUP_ID,DOCUMENT,CONTRACT_TYPE) VALUES(?,?,?,?)";
	public static final String PAYMENT_SELECT_QUERY = "SELECT * FROM PAYMENT WHERE CAK_NO=?";
	public static final String PAYMENT_SELECT_DOWNLOAD_QUERY = "SELECT FILENAME, DOCUMENT FROM PICKUP_SCHEDULE WHERE CAK_NO=?";
	public static final String PAYMENT_INSERT_QUERY = "INSERT INTO PAYMENT(CAK_NO,STATUS,DATE,AOMUNT,CONTRACT_TYPE,DOCUMENT,FILENAME) VALUES(?,?,?,?,?,?)";
	public static final String PAYMENT_UPDATE_QUERY = "UPDATE PAYMENT SET CAK_NO=?,STATUS=?,DATE=?,AOMUNT=?,CONTRACT_TYPE=?,DOCUMENT=?,FILENAME=?) WHERE CAK_NO=?";
	public static final String MRKTINFO_SELECT_QUERY = "SELECT * FROM MARKET_INFORMATION WHERE MARK_ID =?";
	public static final String MRKTINFO_INSERT_QUERY = "INSERT INTO MARKET_INFORMATION(HEADING,DETAILS,MARK_ID,STATUS,CONTRACT_TYPE) VALUES(?,?,?,?,?)";
	public static final String MRKTINFO_UPDATE_QUERY = "UPDATE MARKET_INFORMATION SET HEADING=?,DETAILS=?,STATUS=?,CONTRACT_TYPE=? WHERE MARK_ID=?";
	public static final String MRKTINFO_SELECT_ALL = "SELECT * FROM MARKET_INFORMATION";
	public static final String MRKTINFO_DELETE_MARKETID = "DELETE FROM MARKET_INFORMATION MARK_ID =?";
	public static final String INVENTORY_SELECT_QUERY = "SELECT * FROM INVENTORY WHERE CAK_NO=?";
	public static final String INVENTORY_SELECT_PICKUPID_QUERY = "SELECT * FROM INVENTORY WHERE PICKUP_ID=?";
	public static final String INVENTORY_INSERT_QUERY = "INSERT INTO INVENTORY(CARGO,TRUCKS_NO,BARGE_NO,TIME_IN,WEIGHT_IN,TIME_OUT,WEIGHT_OUT,TOTAL_WEIGHT,PACKING,MODE,LOCATION,PICKUP_ID,CAK_NO,CONTRACT_TYPE) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
	public static final String INVENTORY_UPDATE_QUERY = "UPDATE INVENTORY SET CARGO=?,TRUCKS_NO=?,BARGE_NO=?,TIME_IN=?,WEIGHT_IN=?,TIME_OUT=?,WEIGHT_OUT=?,TOTAL_WEIGHT=?,PACKING=?,MODE=?,LOCATION=?,PICKUP_ID=?,CAK_NO=?,CONTRACT_TYPE=? WHERE CAK_NO=?";
	public static final String CONTRACT_SELECT_QUERY = "SELECT * FROM CONTRACT WHERE CAK_NO=?";
	public static final String CONTRACT_INSERT_QUERY = "INSERT INTO CONTRACT(CAK_NO,APPROVED_QTY,CONTRACT_TYPE,STATUS,CUSTOMER_ID) VALUES(?,?,?,?,?)";
	public static final String CODE_TYPE_SELECT_QUERY = "SELECT * FROM CODE_TYPE WHERE CODE_ID=?";
	public static final String CODE_TYPE_INSERT_QUERY = "INSERT INTO CODE_TYPE(CODE,DESCRIPTION,LANGUAGE,CODE_ID,GROUP_ID) VALUES(?,?,?,?,?)";
	public static final String CHAT_SELECT_QUERY = "SELECT * FROM CHAT WHERE USER_ID=?";
	public static final String CHAT_INSERT_QUERY = "INSERT INTO CHAT(USER_ID,CAK_NO,CHENNAL_ID,DOCUMENT,MESSAGE_DETAILS,CONTRACT_TYPE) VALUES(?,?,?,?,?,?)";
	public static final String ARRIVAL_SCHDL_SELECT_QUERY = "SELECT * FROM ARRIVAL_SCHEDULE";
	public static final String ARRIVAL_SCHDL_INSERT_QUERY = "INSERT INTO ARRIVAL_SCHEDULE(CARGO,VOLUME,TENDERED,SHIPMENT_PERIOD,VESSEL_NAME,WAREHOUSE,ETA,CONTRACT_TYPE,CAK_NO) VALUES(?,?,?,?,?,?,?,?,?)";
	public static final String ARRIVAL_SCHDL_UPDATE_QUERY = "UPDATE ARRIVAL_SCHEDULE SET CARGO=?,VOLUME=?,TENDERED=?,SHIPMENT_PERIOD=?,VESSEL_NAME=?,WAREHOUSE=?,ETA=?,CONTRACT_TYPE=?,CAK_NO=? WHERE CAK_NO =?";
	public static final String USERTOKEN_SELECT_QUERY = "SELECT * FROM USER_TOKEN_MAPPING WHERE USER_ID=?";
	public static final String USERTOKEN_INSERT_QUERY = "INSERT INTO USER_TOKEN_MAPPING(USER_ID,USER_TOKEN,TOKEN_DESC) VALUES(?,?,?)";
	public static final String SERVICECONTRACT_SELECT_ALL = "SELECT * FROM SERVICE_CONTRACTS ";
	public static final String SERVICECONTRACT_BYID = "SELECT * FROM SERVICE_CONTRACTS WHERE CAK_NO =?";
	public static final String SERVICECONTRACT_INSERT_QUERY = "INSERT INTO SERVICE_CONTRACTS(CAKNO,CAKDATE,COMMODITY,QUANTITY,RECEIVED,BALANCESTOCK,CONTRACTTYPE,CUSTOMERID) VALUES(?,?,?,?,?,?,?,?)";
	public static final String SERVICECONTRACT_UPDATE_QUERY = "UPDATE SERVICE_CONTRACTS SET CAKDATE=?,COMMODITY=?,QUANTITY=?,RECEIVED=?,BALANCESTOCK=?,CONTRACTTYPE=?,CUSTOMERID=? WHERE CAKNO=?";
	public static final String ACTUAL_ALERT_SELECT_QUERY = "SELECT * FROM ACTUAL_ALERT";
}
